### PR TITLE
Pygobject

### PR DESCRIPTION
**Pull request by bletham**
Merge in all of the updates for v0.6:
- The entire codebase was migrated from python2 to python3, and from Gtk2/PyGTK to Gtk3/PyGObject.
- The user can now specify which fields to include on the printouts, including fields that are computed from other fields by providing a Python expression.
- During project creation, the user can specify to include "Pace" on the results printouts.
- The user can specify the field according to which results will be ranked (previously had to be Time), and can also choose different ranking fields for each division, if so desired.
- Project settings (divisions, printout fields, and ranking fields) can be edited, from the main window menu.
- Registration data can be edited from the timing window, allowing for easy correction of errors that are observed in the printouts.
- We no longer use any stock icon functionality, which was deprecated in Gtk 3.1. Icon buttons are manually created.
- First name, Last name, and Gender are no longer required registration fields.
- Various UI changes (moving buttons around, renaming things) based on user feedback.

### CODE REVIEW

**Comment by sponce** [comment]
That's great job ! I'm already testing this version for a race that I organize on the 19th of May :-)

The nice part is that it's a team race and thus I needed to remove the required First Name, Last Name and Gender. I was considering working on it when this came :-) I feel lucky now.

However, I have one more thing to work on (and I'll do a pull request when it's there), which is to be able to set the category at import time. For my teams, I have 6 people each time, and a complex category system taking into account genders (men, women and mixed categories), ages (sum of them, but also min) and whether all runners belong to the same working unit or not :-P
So I have the category ready to be imported, but there is no way I compute it in fstimer unless I import massive amount of useless data.

**Comment by bletham** [comment]
Awesome, I look forward to hearing how the race goes!
Yeah having flexibility in the fields was really important, and I loved the advanced ranking you made which makes it so really everything is customizable. (Except Age which will take a little more effort).

If the category is a string with several possible options, then you should be able to do this as-is by creating a "category" field of type combobox which contains all of the possible categories. Then you can create divisionals based on "category == ___", like it is with gender in the demo.

**Comment by sponce** [comment]
The race went perfectly well, as usual with your tool. I had to fix 2 small bugs though, I'll do a pull request soon, nothing major, more details, but annoying when you hit them.
Otherwise, your idea for Category worked greatly. I still commented the entry for Age in the list of required fields so I did not have to fill it when stupid values (a team does not really have an age !), but apart from that, all was ok.
Makes me think that Age should not be required, but that Category definitions should then be entered manually (or no category classification is nothing is provided). For next release !

**Comment by bletham** [comment]
Awesome. I'd definitely like Age to be optional as well. The tricky thing for now is that it is treated as a special case when making divisions, since it is an entrybox but you can specify ranges (so it is assumed to be int).
Probably the right thing to do is to be able to identify an entrybox as a numeric type, and then that will make it possible to use a range condition on that entrybox when creating divisions. Hopefully next release!

**Pull request merged**
